[project]
name = "lab-tools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.4.0",
    "pytest>=9.0.2",
    "sympy>=1.14.0",
    "uncertainties>=3.2.3",
]
